name: Docker Image CI - Orchestrator

env:
  DOCKER_IMAGE: orchestrator
  
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_ORG_TOKEN }}

    - name: Build the Docker image
      run: docker build --no-cache . --file Dockerfile --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest

    - name: Push the Docker image
      run: docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
