name: Docker Image CI - Orchestrator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_ORG_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/modapto/orchestrator:latest

    - name: Push the Docker image
      run: docker push ghcr.io/modapto/orchestrator:latest
